name: Multi-distro, Linux CI

on: [push, pull_request]

jobs:
  test-installation:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - distro: "ubuntu:latest"
            script: "ubuntusysteminstall.sh"
            pkg-manager: "apt-get"
            
          - distro: "fedora:latest"
            script: "rhelsysteminstall.sh"
            pkg-manager: "dnf"

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Test ${{ matrix.script }} on ${{ matrix.distro }}

        run: |
          docker run --rm \
            -v $ {{ github.workspace }}:/workspace \
            -w /workspace \
            ${{ matrix.distro }} \
            bash -c "

              if ['${{ matrix.pkg-manager }} ' = 'apt-get' ]; then
                apt-get update && apt-get install -y sudo
              elif ['${{ matrix.pkg-manager }} ' = 'dnf' ]; then
                dnf install -y sudo
              fi

              bash ./${{ matrix.script }}
            "
          

          
